### ISSUE TITLE
Lichess board API

### ISSUE THREAD

**Issue by ornicar** [karayaman/Play-online-chess-with-real-chess-board#12]
Very cool project, congrats.

Unfortunately it currently breaks the lichess terms of service. Indeed, programmatic usage of the GUI is strictly forbideen. See https://lichess.org/page/fair-play

The great news is that we have an API to do the same thing legally! See:

- [Board API announcement](https://lichess.org/blog/XlRW5REAAB8AUJJ-/welcome-lichess-boards)
- [API doc](https://lichess.org/api#tag/Board)
- [Example implementation](https://github.com/lichess-org/api-demo)
- [Live demo](https://lichess-org.github.io/api-demo/)

Please replace the programmatic GUI mouse clicks with API calls, to avoid users of this project from being banned from lichess.

**Comment by karayaman** [comment]
Hi Thibault, thank you very much for your interest to the project!
I really don't want this project to break the Lichess terms of service. Indeed, it supports Lichess Board API and it has Lichess only features like:
- Start from position
- Takeback
- Promotion piece selection
But, I guess this is not enough, right? Because it still contains programmatic GUI mouse clicks option. 
The thing is, if I removed this option, that would be a huge downgrade. Because, it is the only way to make it work with other chess website/programs. Also it supports recording OTB games (see [Test of automatic recording of DGT Centaur games](https://www.youtube.com/watch?v=j7apOxAJeO8) ) which can't be implemented using Lichess Board API as far as I know.  It is really interesting that even board manufacturers use programmatic GUI mouse clicks (see [Online chess revolution comes from Certabo](https://www.certabo.com/online-chess-revolution-comes-from-certabo/) ). 
What if I create a Lichess-only version of this project that does not contain programmatic GUI mouse clicks option? Let me know what you think.

**Comment by ornicar** [comment]
Awesome that it supports the Lichess API, thanks for that.

I think you should prevent the mouseclicking from happening on Lichess whatsoever.

To record OTB games, we have much better: create a broadcast to livestream the games with world championship tier tools: https://lichess.org/broadcast

- Broadcast API https://lichess.org/api#tag/Broadcasts
- Push PGN to a broadcast round https://lichess.org/api#operation/broadcastPush

**Comment by tttiago** [comment]
Hey! First of all, congrats for the great project.

I actually modified it for the sole purpose of broadcasting multiple live games to Lichess, using the Broadcast API. It has already been trialed during an official team match and now I will use it to broadcast a classical tournament at my chess club. Repo at https://github.com/tttiago/ChessBroadcaster.

If you want to adapt your project to use the API instead of mouse clicks, you can grab my code, at least for game recording. I'm also available to collaborate in order integrate the broadcast feature in your project, if you want to follow that path.

**Comment by karayaman** [comment]
As a solution to this issue, I've decided to create Lichess-only version of this project [Lichess with a real board](https://github.com/karayaman/lichess-with-a-real-board) which does not contain programmatic usage of the GUI.

Although it's just a downgraded version of this project, I'm planning to study the links you have shared and add more features to it.

**Comment by ornicar** [comment]
Excellent. You could [make a blog post](https://lichess.org/blog/community) to introduce it to the lichess community when you think the time is right. A demo video would illustrate it nicely. Let me know if that happens and I'll see if we can feature it.
